In [ ]:
pip install numpy opencv-python torch

In [5]:
# 一维的向量合并, axis = 0 意思是在x轴合并

import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6,7])
np.concatenate((a, b), axis=0)

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
# 二维的向量合并, axis = 0 意思是在x轴合并
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
# 二维的向量合并, axis = 1 意思是在y轴合并, 在Y轴上的elements合并在一起,注意，columns必须相同才能合并
import numpy as np

a = np.array([[1, 2, 3], [3, 4, 5]])
b = np.array([[5, 6], [7,8]])
np.concatenate((a, b), axis=1)

array([[1, 2, 3, 5, 6],
       [3, 4, 5, 7, 8]])

In [35]:
# 三维的向量合并, axis = 2，意思是去到最小单位的数组进行elements合并
import numpy as np

a = np.array([[[1, 2], [3, 4]],
              [[5, 6], [7, 8]],
              [[9, 1], [1, 1]]])

b = np.array([[[2, 3], [3, 4]],
              [[1, 2], [3, 4]],
              [[1, 2], [3, 4]]])
np.concatenate((a, b), axis=2)



array([[[1, 2, 2, 3],
        [3, 4, 3, 4]],

       [[5, 6, 1, 2],
        [7, 8, 3, 4]],

       [[9, 1, 1, 2],
        [1, 1, 3, 4]]])

In [7]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b.T), axis=1)

b.T
a.T

array([[1, 3],
       [2, 4]])

In [2]:
import torch
torch.ones(1).float()

ModuleNotFoundError: No module named 'torch'

In [8]:
import torch
torch.tensor([1.]).float()

tensor([1.])

In [33]:
epoch = 902

if (epoch // 50) % 2 == 0:
        print('A')
else:
        print('B')

loss = print(1) if (epoch // 50) % 2 == 0 else print(2)

A
1


In [23]:
import cv2
import numpy as np

# Read the image
image = cv2.imread('1.png')
image2 = cv2.imread('2.png')

# Create a window list and append the image
window = []
window.append(image)
window.append(image2)

# Convert the list to a NumPy array and transpose the dimensions
window = np.array(window)
print('The window shape',window.shape)

window = np.transpose(window, (3, 0, 1, 2))

# Set the latter half of the channels to zero
window[:, :, window.shape[2]//2:] = 255.
print('The transpose window shape',window.shape)

# Transpose back to the original dimensions
window = np.transpose(window, (1, 2, 3, 0))

# Convert the 4D array back to 3D by selecting the first image in the batch
output_image = window[0]

# Save the modified image
cv2.imwrite('out1.png', output_image)
cv2.imwrite('out2.png', window[1])


The window shape (2, 384, 512, 3)
The transpose window shape (3, 2, 384, 512)


True

In [32]:
import torch

y = [1,1,0,0]
y_tensor = torch.FloatTensor(y)
y_tensor

y_tensor.unsqueeze(1)

tensor([[1.],
        [1.],
        [0.],
        [0.]])