In [24]:
# 一维的向量合并, axis = 0 意思是在x轴合并

import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6,7])
np.concatenate((a, b), axis=0)

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
# 二维的向量合并, axis = 0 意思是在x轴合并
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
# 二维的向量合并, axis = 1 意思是在y轴合并, 在Y轴上的elements合并在一起,注意，columns必须相同才能合并
import numpy as np

a = np.array([[1, 2, 3], [3, 4, 5]])
b = np.array([[5, 6], [7,8]])
np.concatenate((a, b), axis=1)

array([[1, 2, 3, 5, 6],
       [3, 4, 5, 7, 8]])

In [35]:
# 三维的向量合并, axis = 2，意思是去到最小单位的数组进行elements合并
import numpy as np

a = np.array([[[1, 2], [3, 4]],
              [[5, 6], [7, 8]],
              [[9, 1], [1, 1]]])

b = np.array([[[2, 3], [3, 4]],
              [[1, 2], [3, 4]],
              [[1, 2], [3, 4]]])
np.concatenate((a, b), axis=2)



array([[[1, 2, 2, 3],
        [3, 4, 3, 4]],

       [[5, 6, 1, 2],
        [7, 8, 3, 4]],

       [[9, 1, 1, 2],
        [1, 1, 3, 4]]])

In [7]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b.T), axis=1)

b.T
a.T

array([[1, 3],
       [2, 4]])